"""Profile of the Genesis wall types (0..14) and the evidence for what they mean -> genesis_maps/WALL_TYPES.md

usage: python wall_types.py genesis_maps.json map_events.json OUT.md
Evidence used: (1) engine: 0x14C9A reads a lock only where the wall type is non-zero, 0x4DAA (view distance) stops at the
first non-zero wall; (2) data: how many maps become fully connected when a type is passable (leave-one-out);
(3) facing-specific step events print texts about a specific door, so the wall type on that exact side names the door."""
import sys, json, collections

maps = json.load(open(sys.argv[1]))['maps']
ev = json.load(open(sys.argv[2]))
S = ['north', 'east', 'south', 'west']; DY = [-1, 0, 1, 0]; DX = [0, 1, 0, -1]
LABEL = {   # (kind, confidence, note)
    0: ('Open', 'verified', 'no wall; lets the engine see/walk on (0x4DAA stops at the first non-zero wall)'),
    1: ('Wall', 'likely', 'solid wall, the most common type; only 28 sides are locked and all are in map 51 (storeroom windows, barricaded doors)'),
    2: ('Door', 'likely', 'sliding/auto door and stair doors ("DOORS SLIDE OPEN", "EMERGENCY STAIRS")'),
    3: ('Door', 'plausible', 'needed for connectivity in only 2 cases; mostly maps 20/41/51'),
    4: ('Door', 'plausible', 'security doors without a card (map 53) and doors in map 51'),
    5: ('Barrier', 'plausible', 'never needed for connectivity (0 maps change); decoration/window-like walls (maps 10, 60, 41, 20)'),
    6: ('Door', 'likely', 'standard locked door (93% locked); doors with texts "THE DOOR IS LOCKED", main exit, storeroom'),
    7: ('Door', 'likely', 'locked hatch/airlock/cage door (70% locked): cages 1-4, airlock, Talon\'s quarters'),
    8: ('Door', 'plausible', 'locked doors in 30/31/43/61; "ABOUT TO ENTER THE CORE", "IMPENETRABLY LOCKED"'),
    9: ('Door', 'likely', 'very common door type (836 sides) in Spy Ship and Desert Runner Village; 17% locked'),
    10: ('SecretDoor', 'plausible', '"CONCEALED LATCH" event on a type-10 side in map 52; hidden until found'),
    11: ('Door', 'plausible', 'Mercury/Mariposa maps (60/61/62) doors; 1% locked'),
    12: ('Barrier', 'likely', '5 sides, all locked, all in map 51: the acid-frog stockade bars; never needed for connectivity'),
    13: ('Barrier', 'plausible', '32 sides, maps 61/62 only, never locked, never needed for connectivity'),
    14: ('SealedDoor', 'likely', 'doors the scripts keep shut: "SECURITY DOORS ARE SEALED", "FUSED SHUT", "MASSIVE FRONT DOORS", hangar sealed'),
}


def comps(m, passable):
    par = list(range(256))
    def f(a):
        while par[a] != a: par[a] = par[par[a]]; a = par[a]
        return a
    for i in range(256):
        y, x = divmod(i, 16)
        if not m['exists'][i]: continue
        for s in (1, 2):
            ny, nx = y + DY[s], x + DX[s]
            if 0 <= ny < 16 and 0 <= nx < 16 and m['exists'][ny * 16 + nx] and passable(m[S[s]][i]):
                par[f(i)] = f(ny * 16 + nx)
    return len({f(i) for i in range(256) if m['exists'][i]})


prof = collections.defaultdict(collections.Counter); per = collections.defaultdict(collections.Counter)
for m in maps:
    for i in range(256):
        for s in range(4):
            w = m[S[s]][i]
            if w:
                prof[w]['n'] += 1; prof[w]['locked'] += bool(m['lock_' + S[s]][i]); per[w][m['id']] += 1
all_but_1 = set(range(2, 15))
base = sum(comps(m, lambda w: w in all_but_1 or w == 0) for m in maps)
need = {t: sum(comps(m, lambda w, t=t: (w in all_but_1 and w != t) or w == 0) for m in maps) - base for t in all_but_1}
ctx = collections.defaultdict(list)
for mod, r in sorted(ev.items()):
    m = next(x for x in maps if x['id'] == r['map'])
    for s in r['step']:
        if s['facing'] is None: continue
        for x, y in s['cells']:
            w = m[S[s['facing']]][y * 16 + x]
            if w and len(ctx[w]) < 3 and s['texts']: ctx[w].append(f'{mod} ({x},{y}){"NESW"[s["facing"]]}: {s["texts"][0][:60]}')

out = ['# Genesis wall types (0..14)\n',
       'Generated by `tools/genesis_maps/wall_types.py`. Confidence: **verified** = read from the ROM code, **likely** = several independent '
       'pieces of evidence, **plausible** = fits the data, little else. Wall type numbers index the map\'s graphics piece set, so a '
       'type can look different from map to map; the *behaviour* classes below are what the scripts rely on.\n',
       f'Connectivity test: with every type except 1 passable, {base} separate areas remain across the 18 maps (11 maps are a single area). '
       'Column "needed" = extra separate areas appearing when that one type is made impassable again.\n',
       '| type | kind | confidence | sides | locked | needed | maps (sides) | note / script texts |', '|---|---|---|---|---|---|---|---|']
for t in range(15):
    k, conf, note = LABEL[t]
    c = prof[t]
    maps_s = ' '.join(f'{k2:02X}:{v}' for k2, v in sorted(per[t].items(), key=lambda kv: -kv[1])[:5])
    lk = f"{100 * c['locked'] // c['n']}%" if c['n'] else '-'
    ex = ' / '.join(ctx[t]) if ctx[t] else ''
    out.append(f"| {t} | {k} | {conf} | {c['n'] if t else '-'} | {lk} | {need.get(t, '-')} | {maps_s} | {note}{('. ' + ex) if ex else ''} |")
out += ['\nNot found: a movement routine that tests the wall type itself. The only verified movement gate is the lock field '
        '(0x53F8: blocked when bit 0 is set) plus the script flag [9DBF]=255 that scripts set to cancel a step. How the engine keeps the party '
        'out of plain walls is therefore still unconfirmed; the classification above is inferred from data and script texts.\n',
        'Even with every type passable, maps 10, 41, 51 and 63 stay split into several areas (their explorable cells are not adjacent); stairs, teleports or scripted jumps join those.']
open(sys.argv[3], 'w').write('\n'.join(out) + '\n')
print('wrote', sys.argv[3])
